logging:
    level:
        root: INFO

server:
    port: 8080

spring:
    application:
        name: gu
    data:
        redis:
            host: 192.168.0.55
            port: 6379

    websocket:
        message-size: 81920

    servlet:
        multipart:
            max-file-size: 5000MB
            max-request-size: 5000MB
            location: ${user.dir/uploads}

app-config:
    file-upload:
        thumbnail-path: /thumbnail
        unzip-path: /images
        base-path: ${user.dir}
        upload-folder: /
        max-size: 20971520000

