server:
    port: 8080

spring:
    application:
        name: gu
#    data:
#        redis:
#            host: 192.168.0.55
#            port: 6379
#    # JPA
#    jpa:
#        hibernate:
#            ddl-auto: update
#            naming:
#                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        properties:
#            hibernate:
#                default_batch_fetch_size: 5

    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3305/sys?serverTimezone=Asia/Seoul
        username: root
        password: 12345678
#    sql:
#        init:
#            encoding: UTF-8
#            mode: always
#    mvc:
#        throw-exception-if-no-handler-found: true
#    web:
#        resources:
#            add-mappings: false
#
#    servlet:
#        multipart:
#            max-file-size: 5000MB
#            max-request-size: 5000MB
#            location: ${user.dir/uploads}

